# Data Processing - Assignment 1

In this assignment, we focus on the basics of Python programming. You are expected to have Python 3 (Anaconda) installed and you are supposed to write your code in a Jupyter notebook and submit the .ipynb file and PDF of the notebook.

## Fundamentals (30 points)

- Import NumPy and create 2 arrays with the same length and another one with a different length (3 arrays in total).

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

- Perform at least three operations of your choice on arrays of the same size.

In [2]:
print(np.multiply(a,b))
print(np.reciprocal(a))
print(np.power(b,2))

[ 4 10 18]
[1 0 0]
[16 25 36]


- Perform at least three operations of your choice on one element from two arrays. 

In [3]:
print(np.add(a[0],b[2]))
print(np.mod(c[1], a[2]))
print(b[2]**c[0])

7
2
279936


- Create four variables containing a string, integer, float, and boolean and try to cast them to (in order) boolean, float, integer, and string. 

In [4]:
d = 'abc'
e = 123
f = 12.3
g = True

h = bool(d)
i = float(e)
j = int(f)
k = str(g)

print(type(h))
print(type(i))
print(type(j))
print(type(k))

<class 'bool'>
<class 'float'>
<class 'int'>
<class 'str'>


## Control flow (10 points)

- Create an array containing numbers 1 to 10. Iterate through the array using a for a loop. Inside the for loop use some if statement to print the numbers "four" instead of 4 and "eight" instead of 8, otherwise print the digit number. 

In [5]:
l = np.array([1,2,3,4,5,6,7,8,9,10])
for i in l:
    if(i==4):
        print("four")
    elif(i==8):
        print("eight")
    else:
        print(i)

1
2
3
four
5
6
7
eight
9
10


## Data Structure (30 points)

- Create a tuple containing 3 numbers and a list containing 5 numbers. Unpack the tuple into 3 different variables and print them. Then try to remove an element from the list and instead insert one of the variables that were the result of unpacked tuple. Finally, slice and sort the first 3 elements of the list. 

In [6]:
m = 1,2,3
n = [4,5,6,7,8]

o,p,q = m
print (o)
print (p)
print (q)

n.pop()
print(n)
n.insert(2,o)
print(n)

r = n[0:3]
r.sort()
print(r)

1
2
3
[4, 5, 6, 7]
[4, 5, 1, 6, 7]
[1, 4, 5]


- Create a dictionary with these keys: 'int', 'float', 'string', 'boolean', 'list', 'set', 'tuple' and 'dict' and for each key, assign the value of that specific type. For instance, you should create a temporary small dictionary to assign to the 'dict'. 

In [7]:
s = {'int':1,'float':1.1,'string':'abc','boolean':False,'list':[1,2,3],'set':set([1,2,3,4]),'tuple':(1,2),'dict':{'abc':123}}
print(s.keys())
print(s.values())

dict_keys(['int', 'float', 'string', 'boolean', 'list', 'set', 'tuple', 'dict'])
dict_values([1, 1.1, 'abc', False, [1, 2, 3], {1, 2, 3, 4}, (1, 2), {'abc': 123}])


## Sequence Function (10 points)

Create a list containing letters 'a' to 'f', then using a for loop and proper sequence function, produce the following output: 

3 --> a 

4 --> b

5 --> c 

6 --> d

7 --> e 

8 --> f 

In [8]:
t = ['a','b','c','d','e','f']
for index,letter in enumerate(t):
    print(str(index+3) + ' --> ' + str(letter) + '\n')

3 --> a

4 --> b

5 --> c

6 --> d

7 --> e

8 --> f



## Copying (10 points)

By copying the previous list, create a new variable containing the same 'a' to 'f' elements from the previous list. Change an element in one of the variables and make sure the other doesn't change. 

In [9]:
u = t.copy()
print(u)

u.pop()
print(u)
print(t)

['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e', 'f']


## Exception Handling (10 points)

Create a variable containing a tuple object. Then try to change its first element the way you change an element in a list and see what kind of error you will get. Then try to catch handle the error and instead of the error print "Tuples are immutable :)" 

In [10]:
v = (1,1,2,3,4,5)  
try:
    v[0] = 0
except TypeError:
    print ("Tuples are immutable :)")

Tuples are immutable :)
